Repository CAPSTON-EIGHT/EIGHT_SERVER, pull requests merged in 2023-08, with the labels that each got.

#3 [FEAT] 작품 MVC 패턴 및 작품 엔티티 생성
  src/main/java/com/example/eight/artwork/controller/ArtworkController.java
  src/main/java/com/example/eight/artwork/entity/Element.java
  src/main/java/com/example/eight/artwork/entity/Part.java
  src/main/java/com/example/eight/artwork/entity/Relic.java
  src/main/java/com/example/eight/artwork/entity/SolvedElement.java
  src/main/java/com/example/eight/artwork/entity/SolvedPart.java
  src/main/java/com/example/eight/artwork/entity/SolvedRelic.java
  src/main/java/com/example/eight/artwork/repository/RelicRepository.java
  src/main/java/com/example/eight/artwork/service/ArtworkService.java
Labels: 🎉 infra, 🎱 feature

#4 [FEAT] 유저 엔티티 생성 및 구글 Oauth 초기 설정
  build.gradle
  src/main/java/com/example/eight/user/entity/Role.java
  src/main/java/com/example/eight/user/entity/User.java
  src/main/java/com/example/eight/user/repository/UserRepository.java
  src/main/java/com/example/eight/user/service/UserService.java
  src/main/resources/application-oauth.properties
  src/main/resources/application.properties
  src/test/java/com/example/eight/user/UserTest.java
Labels: 🎉 infra, 🎱 feature

#10 [UPDATE] 작품 부분 정보 조회 API 응답에 뱃지 추가
  src/main/java/com/example/eight/artwork/controller/ArtworkController.java
  src/main/java/com/example/eight/artwork/dto/PartsResponseDto.java
  src/main/java/com/example/eight/artwork/service/ArtworkService.java
Labels: ✏️ refactor

#13 [FEAT] 소셜 로그인 & Jwt 토큰 발급 및 검증 구현
  build.gradle
  src/main/java/com/example/eight/global/config/SecurityConfig.java
  src/main/java/com/example/eight/global/jwt/JwtAuthFilter.java
  src/main/java/com/example/eight/global/jwt/JwtService.java
  src/main/java/com/example/eight/global/oauth2/dto/OAuthAttributes.java
  src/main/java/com/example/eight/global/oauth2/handler/OAuth2LoginFailureHandler.java
  src/main/java/com/example/eight/global/oauth2/handler/OAuth2LoginSuccessHandler.java
  src/main/java/com/example/eight/global/oauth2/service/CustomOAuth2UserService.java
  src/main/java/com/example/eight/user/Role.java
  src/main/java/com/example/eight/user/SocialType.java
  src/main/java/com/example/eight/user/controller/UserController.java
  src/main/java/com/example/eight/user/dto/JwtTokenDto.java
  src/main/java/com/example/eight/user/dto/ResponseDto.java
  src/main/java/com/example/eight/user/entity/User.java
  src/main/java/com/example/eight/user/repository/UserRepository.java
  src/main/java/com/example/eight/user/service/UserService.java
  src/main/resources/application-oauth.properties
  src/main/resources/application.properties
  src/test/java/com/example/eight/global/jwt/JwtServiceTest.java
  src/test/java/com/example/eight/user/UserTest.java
Labels: 🎱 feature

#14 [FEAT] 작품 태그 인식 API 구현
  build.gradle
  src/main/java/com/example/eight/artwork/controller/ArtworkController.java
  src/main/java/com/example/eight/artwork/dto/TagRequestDto.java
  src/main/java/com/example/eight/artwork/dto/TagResponseDto.java
  src/main/java/com/example/eight/artwork/repository/RelicRepository.java
  src/main/java/com/example/eight/artwork/service/ArtworkService.java
Labels: 🎱 feature, 🖼 ocr
