Repository CAPSTON-EIGHT/EIGHT_SERVER, pull requests merged in 2023-10, with the labels that each got.

#40 [FEAT] 토큰 재발급 API 추가
  src/main/java/com/example/eight/artwork/controller/ArtworkController.java
  src/main/java/com/example/eight/global/ResponseDto.java
  src/main/java/com/example/eight/global/config/SecurityConfig.java
  src/main/java/com/example/eight/global/jwt/JwtAuthFilter.java
  src/main/java/com/example/eight/global/jwt/controller/JwtController.java
  src/main/java/com/example/eight/global/jwt/dto/JwtTokenDto.java
  src/main/java/com/example/eight/global/jwt/service/JwtService.java
  src/main/java/com/example/eight/global/oauth2/controller/OauthController.java
  src/main/java/com/example/eight/user/controller/UserController.java
  src/main/java/com/example/eight/user/repository/UserRepository.java
  src/main/resources/application.properties
Labels: 👤 user

#53 [UPDATE] 작품 영문 제목 추가
  .github/workflows/ci.yml
  appspec.yml
  scripts/deploy.sh
  src/main/java/com/example/eight/artwork/dto/PartInfoDto.java
  src/main/java/com/example/eight/artwork/dto/TagResponseDto.java
  src/main/java/com/example/eight/artwork/entity/Relic.java
  src/main/java/com/example/eight/artwork/service/ArtworkService.java
  src/main/java/com/example/eight/global/config/SecurityConfig.java
  src/main/resources/application-oauth.properties
  src/main/resources/application.properties
Labels: 🌟 update

#54 [feature] 전체 작품 조회 API
  src/main/java/com/example/eight/artwork/controller/ArtworkController.java
  src/main/java/com/example/eight/artwork/dto/RelicInfoDto.java
  src/main/java/com/example/eight/artwork/dto/RelicResponseDto.java
  src/main/java/com/example/eight/artwork/service/ArtworkService.java
Labels: 🎱 feature, 🌳 open API

#56 [FEAT] 도감 오버뷰 조회 API 추가
  src/main/java/com/example/eight/artwork/repository/SolvedRelicRepository.java
  src/main/java/com/example/eight/collection/controller/CollectionController.java
  src/main/java/com/example/eight/collection/dto/OverviewDto.java
  src/main/java/com/example/eight/collection/dto/OverviewResponseDto.java
  src/main/java/com/example/eight/collection/service/CollectionService.java
Labels: 🎱 feature

#58 [FIX] API Service Key 변경
  src/main/resources/application-oauth.properties
Labels: 🎉 infra, 🌳 open API, 🤐 fix

#60 [FEAT] 작품의 전체 해설 조회 API
  src/main/java/com/example/eight/artwork/controller/ArtworkController.java
  src/main/java/com/example/eight/artwork/dto/RelicDetailResponseDto.java
  src/main/java/com/example/eight/artwork/repository/PartRepository.java
  src/main/java/com/example/eight/artwork/service/ArtworkService.java
Labels: 🎱 feature, 🌳 open API
