Repository CAPSTON-EIGHT/EIGHT_SERVER, pull requests merged in 2023-09, with the labels that each got.

#16 [FEAT] 유저 프로필 조회 API 구현
  src/main/java/com/example/eight/global/jwt/JwtAuthFilter.java
  src/main/java/com/example/eight/user/controller/UserController.java
  src/main/java/com/example/eight/user/dto/UserProfileDto.java
  src/main/java/com/example/eight/user/service/UserService.java
Labels: 🎱 feature, 👤 user

#17 [FEAT] 작품 부분 정보 조회 API에 공공 API 불러오기 추가
  src/main/java/com/example/eight/artwork/controller/ArtworkController.java
  src/main/java/com/example/eight/artwork/entity/Relic.java
  src/main/java/com/example/eight/artwork/repository/RelicRepository.java
  src/main/java/com/example/eight/artwork/service/ArtworkService.java
  src/main/java/com/example/eight/config/RestTemplateConfig.java
Labels: 🎱 feature, 🌳 open API

#19 [FEAT] 부분의 각 요소 조회 API 추가
  src/main/java/com/example/eight/artwork/controller/ArtworkController.java
  src/main/java/com/example/eight/artwork/dto/ElementInfoDto.java
  src/main/java/com/example/eight/artwork/dto/ElementResponseDto.java
  src/main/java/com/example/eight/artwork/repository/ElementRepository.java
  src/main/java/com/example/eight/artwork/repository/SolvedElementRepository.java
  src/main/java/com/example/eight/artwork/repository/SolvedPartRepository.java
  src/main/java/com/example/eight/artwork/service/ArtworkService.java
  src/main/java/com/example/eight/user/dto/UserProfileDto.java
  src/main/java/com/example/eight/user/service/UserService.java
Labels: 🎱 feature

#23 [FEAT] 전체 부분해설 조회 API 추가
  src/main/java/com/example/eight/artwork/controller/ArtworkController.java
  src/main/java/com/example/eight/artwork/dto/PartDescriptionInfoDto.java
  src/main/java/com/example/eight/artwork/dto/PartDescriptionResponseDto.java
  src/main/java/com/example/eight/artwork/service/ArtworkService.java
Labels: 🎱 feature, 🌳 open API

#24 [CHORE] GitHub Action CI 구축
  .github/workflows/ci.yml
  build.gradle
  gradle/wrapper/gradle-wrapper.properties
  src/main/resources/application.properties
  src/test/java/com/example/eight/global/jwt/JwtServiceTest.java
  src/test/java/com/example/eight/user/UserTest.java
Labels: 🔨build, ⚙CI

#27 [CHORE] GitHub Action과 S3 연동
  .github/workflows/ci.yml
Labels: ⚙CI, 💫deploy, ☁AWS

#29 부분의 해설 및 요소 조회 API 추가
  src/main/java/com/example/eight/artwork/controller/ArtworkController.java
  src/main/java/com/example/eight/artwork/dto/ElementInfoAndPointDto.java
  src/main/java/com/example/eight/artwork/dto/PartDescriptionAndElementResponseDto.java
  src/main/java/com/example/eight/artwork/entity/Relic.java
  src/main/java/com/example/eight/artwork/repository/RelicRepository.java
  src/main/java/com/example/eight/artwork/service/ArtworkService.java
Labels: 🎱 feature
